#!/usr/bin/python 
 
import os 
from string import ascii_letters 
 
file =  open('decrypt.txt','r') 
fileContent=file.read() 
for ewords in fileContent.split(): 
 
    dwords='' 
    for c in ewords: 
        if c in ascii_letters: 
            dwords=dwords+ascii_letters[(ascii_letters.index(c)-2)%len(ascii_letters)] 
        else: 
            dwords+=c 
 
    print dwords
