#!/usr/bin/python

import MySQLdb

# Open database connection
db = MySQLdb.connect("localhost","root","root","Employee" )

# prepare a cursor object using cursor() method
cursor = db.cursor()

# Prepare SQL query to INSERT a record into the database.
sql = """ INSERT INTO employee (id, name, dept, age, salary, location) VALUES (108, 'Ram j', 'Mech', 27, 33000,'India') """
try:
   # Execute the SQL command
   cursor.execute(sql)
   # Commit your changes in the database
   db.commit()
   print "Record inserted sucessfully.."
except:
   # Rollback in case there is any error
   db.rollback()

# disconnect from server
db.close()
