#!/usr/bin/python

a=11 
b=11

if a==b:
	print "%d is equal to %d" %(a,b)
elif a>b:
	print "%d is greater than %d" %(a,b)
else:
	print "%d is lesser than %d" %(a,b)

print ""

print"For loop examples"

for i in range(0,5):
	print i,
print " "

print "Loop with in a loop"
for i in range(1,10):
	for j in range(1,i+1):
		print j,
	print "\n"
