#!/usr/bin/python

print "Hello World"

print 2+1

print 4*5

print 10-5

print 10%2

print 10/2

print "ram\nnaveen\nyamini",

print "ram\tnaveen\tyamini\t"

names=["Abhi","Lasya","Pari"]
print names
print names[0]
print names[-1]
print (names[1])[0]
print (names[0])[2]
print (names[1])[3]

name = "Yaminikanth Chitakala"
print name
print name[0]
print name[-1]
print name[-2]
print name[0:10]
print name[:10]
print name[5:10]
print name[::2]
print name[:21:2]
print name[::-1]
print name[::-2]


nums=[1,2,3,4,5]
print nums
print nums[::2]
print nums[1::2]
print nums[::2]
print nums[::1]


print len(name)
print len(nums)

strings=["Yamini","Abhi","Lasya","Parimala"]
print strings
print (strings[0])[1]
print len(strings)
print strings[2][1]
print strings[3][4]

Alphabets="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
print Alphabets
print len(Alphabets)
print Alphabets[-1]
print Alphabets[0]
print Alphabets[::-1]
print Alphabets[::25]
print Alphabets[::1]
print Alphabets[::2]



