#!/usr/bin/python
import sys

print('Arguments:', len(sys.argv))
#arg = sys.argv[1]
arg='male'
if arg==(sys.argv[1]):
  print "Mr %s %s, you are %d years old right ?" %(sys.argv[2],sys.argv[3],int(sys.argv[4]) + 5)

elif arg!=(sys.argv[1]):
  print "Ms. %s %s, you are %d years only right?" %(sys.argv[2],sys.argv[3],int(sys.argv[4]) - 5)
