#!/usr/bin/python

import os
os.system("clear")
from random import *


class Board():
    def __init__(self):
        self.cells = [" "," "," "," "," "," "," "," "," "," "]

    def display(self):
        print (" %s | %s | %s " %(self.cells[1], self.cells[2],self.cells[3]))
        print ("-----------")
        print (" %s | %s | %s " %(self.cells[4], self.cells[5],self.cells[6]))
        print ("-----------")
        print (" %s | %s | %s " %(self.cells[7], self.cells[8],self.cells[9]))

    def update_cell(self, cell_no):
        if self.cells[cell_no] == " ":
            self.cells[cell_no] = 2

gameboard = Board()

def print_Header():
    print ("Welcome to 1024!\n")
    print ("Press enter to launch the board or move!\n")

print_Header()

#gameboard.display()

while True:
    input=raw_input()
    rand=randint(1,9)
    gameboard.update_cell(rand)
    print("\n")
   # os.system("clear")
    gameboard.display()

