#!/usr/bin/python

class Board(object):
    def cleanboard(self): 
      print "\n" 
      print "  |  | "  
      print "--------" 
      print "  |  | "  
      print "--------" 
      print "  |  | "  
      print "\n"
    

myboard = Board()
myboard.cleanboard()
